title: Projekte
tabs:
  main:
    display: Hauptbereich
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              display: Projekttitel
          -
            handle: description
            field:
              buttons:
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - superscript
                - subscript
              link_noopener: true
              link_noreferrer: true
              target_blank: true
              container: assets
              remove_empty_nodes: trim
              type: bard
              display: Projektbeschreibung
              sortable: false
              replicator_preview: false
              duplicate: false
              actions: false
              validate:
                - required
          -
            handle: logo
            field:
              container: assets
              max_files: 1
              min_files: 1
              type: assets
              display: Projekt-Logo
              width: 50
              sortable: false
              replicator_preview: false
              duplicate: false
              actions: false
              folder: projects
              restrict: true
              validate:
                - required
          -
            handle: link
            field:
              input_type: url
              type: text
              display: Projekt-Link
              width: 50
              sortable: false
              replicator_preview: false
              duplicate: false
              actions: false
          -
            handle: images
            field:
              container: assets
              type: assets
              display: Projektbilder
              sortable: false
              replicator_preview: false
              duplicate: false
              actions: false
              folder: projects
              restrict: true
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
